/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiPdfRouteImport } from './routes/api/pdf'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardResumeIdRouteImport } from './routes/_authenticated/dashboard.$resumeId'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated/dashboard.billing'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCashfreeWebhookRouteImport } from './routes/api/cashfree.webhook'
import { Route as AdminAdminPlansIndexRouteImport } from './routes/_admin/admin.plans.index'
import { Route as AdminAdminTemplatesIndexRouteImport } from './routes/_admin/admin.templates.index'
import { Route as AdminAdminTemplatesTemplateIdRouteImport } from './routes/_admin/admin.templates.$templateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfRoute = ApiPdfRouteImport.update({
  id: '/api/pdf',
  path: '/api/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardResumeIdRoute =
  AuthenticatedDashboardResumeIdRouteImport.update({
    id: '/dashboard/$resumeId',
    path: '/dashboard/$resumeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/dashboard/billing',
    path: '/dashboard/billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCashfreeWebhookRoute = ApiCashfreeWebhookRouteImport.update({
  id: '/api/cashfree/webhook',
  path: '/api/cashfree/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminPlansIndexRoute = AdminAdminPlansIndexRouteImport.update({
  id: '/admin/plans/',
  path: '/admin/plans/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminTemplatesIndexRoute =
  AdminAdminTemplatesIndexRouteImport.update({
    id: '/admin/templates/',
    path: '/admin/templates/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminTemplatesTemplateIdRoute =
  AdminAdminTemplatesTemplateIdRouteImport.update({
    id: '/admin/templates/$templateId',
    path: '/admin/templates/$templateId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/pdf': typeof ApiPdfRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/dashboard/$resumeId': typeof AuthenticatedDashboardResumeIdRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cashfree/webhook': typeof ApiCashfreeWebhookRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/templates/$templateId': typeof AdminAdminTemplatesTemplateIdRoute
  '/admin/plans/': typeof AdminAdminPlansIndexRoute
  '/admin/templates/': typeof AdminAdminTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/pdf': typeof ApiPdfRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/dashboard/$resumeId': typeof AuthenticatedDashboardResumeIdRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cashfree/webhook': typeof ApiCashfreeWebhookRoute
  '/admin': typeof AdminAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/admin/templates/$templateId': typeof AdminAdminTemplatesTemplateIdRoute
  '/admin/plans': typeof AdminAdminPlansIndexRoute
  '/admin/templates': typeof AdminAdminTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/pdf': typeof ApiPdfRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_authenticated/dashboard/$resumeId': typeof AuthenticatedDashboardResumeIdRoute
  '/_authenticated/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cashfree/webhook': typeof ApiCashfreeWebhookRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_admin/admin/templates/$templateId': typeof AdminAdminTemplatesTemplateIdRoute
  '/_admin/admin/plans/': typeof AdminAdminPlansIndexRoute
  '/_admin/admin/templates/': typeof AdminAdminTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/api/pdf'
    | '/admin/users'
    | '/dashboard/$resumeId'
    | '/dashboard/billing'
    | '/api/auth/$'
    | '/api/cashfree/webhook'
    | '/admin/'
    | '/dashboard/'
    | '/admin/templates/$templateId'
    | '/admin/plans/'
    | '/admin/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/pdf'
    | '/admin/users'
    | '/dashboard/$resumeId'
    | '/dashboard/billing'
    | '/api/auth/$'
    | '/api/cashfree/webhook'
    | '/admin'
    | '/dashboard'
    | '/admin/templates/$templateId'
    | '/admin/plans'
    | '/admin/templates'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/api/pdf'
    | '/_admin/admin/users'
    | '/_authenticated/dashboard/$resumeId'
    | '/_authenticated/dashboard/billing'
    | '/api/auth/$'
    | '/api/cashfree/webhook'
    | '/_admin/admin/'
    | '/_authenticated/dashboard/'
    | '/_admin/admin/templates/$templateId'
    | '/_admin/admin/plans/'
    | '/_admin/admin/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPdfRoute: typeof ApiPdfRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCashfreeWebhookRoute: typeof ApiCashfreeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf': {
      id: '/api/pdf'
      path: '/api/pdf'
      fullPath: '/api/pdf'
      preLoaderRoute: typeof ApiPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/$resumeId': {
      id: '/_authenticated/dashboard/$resumeId'
      path: '/dashboard/$resumeId'
      fullPath: '/dashboard/$resumeId'
      preLoaderRoute: typeof AuthenticatedDashboardResumeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/billing': {
      id: '/_authenticated/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cashfree/webhook': {
      id: '/api/cashfree/webhook'
      path: '/api/cashfree/webhook'
      fullPath: '/api/cashfree/webhook'
      preLoaderRoute: typeof ApiCashfreeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/plans/': {
      id: '/_admin/admin/plans/'
      path: '/admin/plans'
      fullPath: '/admin/plans/'
      preLoaderRoute: typeof AdminAdminPlansIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/templates/': {
      id: '/_admin/admin/templates/'
      path: '/admin/templates'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AdminAdminTemplatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/templates/$templateId': {
      id: '/_admin/admin/templates/$templateId'
      path: '/admin/templates/$templateId'
      fullPath: '/admin/templates/$templateId'
      preLoaderRoute: typeof AdminAdminTemplatesTemplateIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminTemplatesTemplateIdRoute: typeof AdminAdminTemplatesTemplateIdRoute
  AdminAdminPlansIndexRoute: typeof AdminAdminPlansIndexRoute
  AdminAdminTemplatesIndexRoute: typeof AdminAdminTemplatesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminTemplatesTemplateIdRoute: AdminAdminTemplatesTemplateIdRoute,
  AdminAdminPlansIndexRoute: AdminAdminPlansIndexRoute,
  AdminAdminTemplatesIndexRoute: AdminAdminTemplatesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardResumeIdRoute: typeof AuthenticatedDashboardResumeIdRoute
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardResumeIdRoute: AuthenticatedDashboardResumeIdRoute,
  AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPdfRoute: ApiPdfRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCashfreeWebhookRoute: ApiCashfreeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
